apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apps
  name: apps
  namespace: default
spec:
  selector:
    matchLabels:
      app: apps
  replicas: 1
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - image: legioownage/backend
        imagePullPolicy: IfNotPresent
        name: backend
      - image: legioownage/frontend
        imagePullPolicy: IfNotPresent
        name: frontend
